// src/app/post/[id]/page.tsx
import Image from 'next/image';
import Link from 'next/link';
import { RelatedPost } from '@/components/RelatedPost';
import { ShareButtons } from '@/components/ShareButtons';
import { CommentSection } from '@/components/CommentSection';
import { AuthorCard } from '@/components/AuthorCard';
import { TableOfContents } from '@/components/TableOfContents';

// This would typically come from your CMS or data source
// Here it's just for demonstration
const getBlogPost = (id: string) => {
  return {
    id,
    title: 'The Future of Generative AI in Content Creation',
    subtitle: 'Exploring how generative AI is revolutionizing the way we create and consume digital content across industries.',
    heroImage: '/api/placeholder/1200/600',
    publishDate: 'April 8, 2025',
    updateDate: 'April 10, 2025',
    readTime: '8 min read',
    category: 'AI Trends',
    tags: ['Generative AI', 'Content Creation', 'Machine Learning', 'Creative AI', 'Future Tech'],
    author: {
      name: 'Alex Chen',
      bio: 'AI researcher and tech enthusiast with over 10 years of experience in machine learning and natural language processing.',
      avatar: '/api/placeholder/100/100',
      role: 'Senior AI Writer',
      twitter: '@alexchen',
    },
    tableOfContents: [
      { id: 'introduction', title: 'Introduction', level: 1 },
      { id: 'current-landscape', title: 'The Current Landscape', level: 1 },
      { id: 'text-generation', title: 'Text Generation Evolution', level: 1 },
      { id: 'image-creation', title: 'AI Image Creation', level: 2 },
      { id: 'video-production', title: 'Video Production', level: 2 },
      { id: 'future-predictions', title: 'Future Predictions', level: 1 },
      { id: 'ethical-considerations', title: 'Ethical Considerations', level: 1 },
      { id: 'conclusion', title: 'Conclusion', level: 1 },
    ],
    content: `
<div id="introduction">
  <h2 class="text-3xl font-bold mb-6">Introduction</h2>
  <p class="mb-4">Generative AI has rapidly evolved from a research curiosity to a transformative force reshaping how content is created, edited, and distributed across various industries. The ability of AI systems to generate human-quality text, realistic images, and even video is fundamentally changing creative workflows and opening new possibilities for content creators.</p>
  <p class="mb-4">In this article, we'll explore the current state of generative AI for content creation, examine key innovations driving the field forward, and consider the implications for creative professionals, businesses, and consumers in the coming years.</p>
</div>

<div id="current-landscape">
  <h2 class="text-3xl font-bold my-8">The Current Landscape</h2>
  <p class="mb-4">The generative AI landscape has undergone tremendous growth in the past three years. Models like GPT-4, Claude, and PaLM have demonstrated remarkable capabilities in natural language generation, while DALL-E, Midjourney, and Stable Diffusion have revolutionized image creation.</p>
  <p class="mb-6">These technologies are rapidly being integrated into existing workflows across industries:</p>
  <ul class="list-disc pl-6 mb-6 space-y-2">
    <li>Marketing teams are using AI to draft copy, generate campaign ideas, and create visual assets</li>
    <li>News organizations are implementing AI assistants for research and initial draft creation</li>
    <li>E-commerce platforms are automatically generating product descriptions and visual variants</li>
    <li>Game developers are using AI to create textures, environments, and NPC dialogue</li>
  </ul>
  <div class="bg-gray-800 rounded-xl overflow-hidden my-8">
    <Image 
      src="/api/placeholder/800/400" 
      alt="AI-generated content examples" 
      width={800} 
      height={400} 
      className="w-full h-auto"
    />
    <p class="text-sm text-gray-400 italic p-4">Examples of content generated by various AI systems in 2025. Notice the significant improvement in coherence and creativity compared to 2023 models.</p>
  </div>
</div>

<div id="text-generation">
  <h2 class="text-3xl font-bold my-8">Text Generation Evolution</h2>
  <p class="mb-4">The evolution of large language models (LLMs) has been nothing short of remarkable. Current-generation LLMs exhibit sophisticated understanding of context, tone, and stylistic nuance that was unthinkable just a few years ago.</p>
  <p class="mb-4">Modern text generation systems can now:</p>
  <ul class="list-disc pl-6 mb-6 space-y-2">
    <li>Adapt writing style to match specific brands or authors</li>
    <li>Generate technically accurate content across specialized domains</li>
    <li>Create long-form content with consistent narrative structure</li>
    <li>Optimize text for specific platforms and audience segments</li>
  </ul>
  <p class="mb-4">Perhaps most importantly, these systems have evolved from mere text generators to collaborative tools that enhance human creativity rather than attempting to replace it.</p>
  
  <blockquote class="border-l-4 border-emerald-500 pl-4 italic my-8">
    <p class="mb-2">"The most effective content strategies today involve human-AI collaboration, where AI handles the routine aspects of content creation while humans focus on strategic decisions, emotional resonance, and innovative thinking."</p>
    <cite class="text-gray-400">— Dr. Sarah Montgomery, Content AI Research Lead at MIT Media Lab</cite>
  </blockquote>
  
  <div id="image-creation">
    <h3 class="text-2xl font-bold my-6">AI Image Creation</h3>
    <p class="mb-4">Diffusion models have transformed visual content creation by enabling the generation of high-quality images from text descriptions. Recent advances have addressed earlier limitations regarding anatomical accuracy, composition control, and stylistic consistency.</p>
    <p class="mb-4">Key developments in AI image generation include:</p>
    <ul class="list-disc pl-6 mb-6 space-y-2">
      <li>Fine-grained control over composition and elements within the image</li>
      <li>Consistent character generation across multiple images</li>
      <li>Seamless style transfer and adaptation</li>
      <li>Integration with 3D modeling pipelines</li>
      <li>Higher resolution output with precise detail control</li>
    </ul>
  </div>
  
  <div id="video-production">
    <h3 class="text-2xl font-bold my-6">Video Production</h3>
    <p class="mb-4">While text and image generation have seen widespread adoption, video generation remains the newest frontier with transformative potential. Early text-to-video models are now being deployed in commercial applications, enabling creators to generate short video clips from descriptive prompts.</p>
    <p class="mb-4">Current capabilities include:</p>
    <ul class="list-disc pl-6 mb-6 space-y-2">
      <li>Generation of 15-60 second clips with coherent motion</li>
      <li>Basic character animation and scene transitions</li>
      <li>Style consistency throughout the video duration</li>
      <li>Integration of generated footage with traditional video assets</li>
    </ul>
    <p class="mb-4">While still emerging, these technologies are already finding application in advertising, social media content, and educational materials.</p>
  </div>
</div>

<div id="future-predictions">
  <h2 class="text-3xl font-bold my-8">Future Predictions</h2>
  <p class="mb-4">The trajectory of generative AI for content creation points toward several key developments in the near future:</p>
  
  <div class="grid grid-cols-1 md:grid-cols-2 gap-6 my-8">
    <div class="bg-gray-800 p-6 rounded-xl">
      <h4 class="text-xl font-bold mb-4">Multimodal Integration</h4>
      <p>Future AI systems will seamlessly work across text, image, audio, and video simultaneously, enabling truly integrated content creation. This will allow for concepts to flow naturally between different media formats within a single creative platform.</p>
    </div>
    
    <div class="bg-gray-800 p-6 rounded-xl">
      <h4 class="text-xl font-bold mb-4">Personalized Content at Scale</h4>
      <p>Content will be increasingly tailored to individual preferences and contexts, with AI enabling 1:1 personalization even for large audiences. This will transform how brands connect with consumers across all touchpoints.</p>
    </div>
    
    <div class="bg-gray-800 p-6 rounded-xl">
      <h4 class="text-xl font-bold mb-4">Interactive Creation Processes</h4>
      <p>AI assistants will evolve from tools that respond to prompts into collaborative partners that engage in nuanced back-and-forth ideation with human creators, suggesting iterations and exploring creative directions.</p>
    </div>
    
    <div class="bg-gray-800 p-6 rounded-xl">
      <h4 class="text-xl font-bold mb-4">Democratized Production</h4>
      <p>Advanced content creation capabilities will become accessible to individuals and small businesses without specialized training, fundamentally changing who can produce professional-quality content and at what cost.</p>
    </div>
  </div>
</div>

<div id="ethical-considerations">
  <h2 class="text-3xl font-bold my-8">Ethical Considerations</h2>
  <p class="mb-4">As generative AI becomes more capable and widespread, several important ethical considerations must be addressed:</p>
  
  <div class="overflow-x-auto my-8">
    <table class="min-w-full bg-gray-800 rounded-xl overflow-hidden">
      <thead>
        <tr>
          <th class="px-6 py-3 text-left text-sm font-medium text-emerald-400 uppercase tracking-wider border-b border-gray-700">Concern</th>
          <th class="px-6 py-3 text-left text-sm font-medium text-emerald-400 uppercase tracking-wider border-b border-gray-700">Impact</th>
          <th class="px-6 py-3 text-left text-sm font-medium text-emerald-400 uppercase tracking-wider border-b border-gray-700">Potential Solutions</th>
        </tr>
      </thead>
      <tbody class="divide-y divide-gray-700">
        <tr>
          <td class="px-6 py-4 whitespace-nowrap text-sm font-medium">Copyright and Ownership</td>
          <td class="px-6 py-4 text-sm">Questions around who owns AI-generated content and rights of original creators whose work trained the models</td>
          <td class="px-6 py-4 text-sm">New licensing frameworks, attribution systems, compensation models for training data contributors</td>
        </tr>
        <tr>
          <td class="px-6 py-4 whitespace-nowrap text-sm font-medium">Misinformation</td>
          <td class="px-6 py-4 text-sm">Potential for creating convincing fake content at unprecedented scale</td>
          <td class="px-6 py-4 text-sm">Content provenance systems, digital watermarking, improved detection tools</td>
        </tr>
        <tr>
          <td class="px-6 py-4 whitespace-nowrap text-sm font-medium">Labor Displacement</td>
          <td class="px-6 py-4 text-sm">Transformation of creative professions and potential job losses</td>
          <td class="px-6 py-4 text-sm">Reskilling programs, focus on human-AI collaboration, universal basic income</td>
        </tr>
        <tr>
          <td class="px-6 py-4 whitespace-nowrap text-sm font-medium">Bias and Representation</td>
          <td class="px-6 py-4 text-sm">Perpetuation or amplification of existing biases in content</td>
          <td class="px-6 py-4 text-sm">Diverse training data, bias detection tools, inclusive development teams</td>
        </tr>
      </tbody>
    </table>
  </div>
  
  <p class="mb-4">Industry leaders and policymakers are increasingly focusing on these challenges, with several initiatives emerging to establish ethical frameworks for generative AI deployment in creative industries.</p>
</div>

<div id="conclusion">
  <h2 class="text-3xl font-bold my-8">Conclusion</h2>
  <p class="mb-4">Generative AI for content creation stands at an inflection point, with the technology simultaneously maturing for mainstream adoption while continuing to evolve at a remarkable pace. The coming years will likely see generative AI become an integral part of content creation workflows across all industries and creative disciplines.</p>
  <p class="mb-4">The most successful implementations will be those that thoughtfully blend AI capabilities with human creativity, judgment, and strategic thinking. Rather than a replacement for human creativity, generative AI is emerging as a powerful amplifier of human creative potential when deployed conscientiously.</p>
  <p class="mb-6">As these technologies continue to evolve, ongoing dialogue between technologists, creative professionals, ethicists, and policymakers will be essential to ensure that generative AI enhances rather than diminishes the creative landscape.</p>
</div>
    `,
  };
};

const getRelatedPosts = () => {
  return [
    {
      id: '2',
      title: 'Multi-modal AI: Bridging Text, Image and Audio Generation',
      excerpt: 'How the latest AI systems are breaking down barriers between different forms of media creation.',
      imageUrl: '/api/placeholder/400/250',
      category: 'Research',
    },
    {
      id: '3',
      title: "The Creative's Guide to Effective AI Prompting",
      excerpt: 'Master the art of crafting effective prompts to get the best results from generative AI tools.',
      imageUrl: '/api/placeholder/400/250',
      category: 'Tutorials',
    },
    {
      id: '4',
      title: 'AI Content Detection: Myths and Realities',
      excerpt: 'An in-depth look at the current state of AI content detection technology.',
      imageUrl: '/api/placeholder/400/250',
      category: 'Analysis',
    },
  ];
};

export default function BlogPost({ params }: { params: { id: string } }) {
  const post = getBlogPost(params.id);
  const relatedPosts = getRelatedPosts();
  
  return (
    <main className="min-h-screen bg-gray-900 text-gray-100">
      {/* Navigation Bar - You can include the same navbar component here */}
      {/* For brevity, I'm not including it in this example */}
      
      {/* Hero Section */}
      <section className="w-full bg-gradient-to-b from-gray-950 to-gray-900 pt-20 pb-12">
        <div className="container mx-auto px-4 max-w-screen-xl">
          <div className="flex flex-col items-center text-center mb-8">
            <span className="bg-emerald-500 text-gray-900 text-sm font-medium px-3 py-1 rounded mb-6">
              {post.category}
            </span>
            <h1 className="text-4xl md:text-5xl lg:text-6xl font-bold mb-6 max-w-4xl">
              {post.title}
            </h1>
            <p className="text-xl text-gray-300 mb-8 max-w-3xl">
              {post.subtitle}
            </p>
            
            <div className="flex items-center space-x-6">
              <div className="flex items-center">
                <div className="relative h-12 w-12 rounded-full overflow-hidden mr-4">
                  <Image
                    src={post.author.avatar}
                    alt={post.author.name}
                    fill
                    className="object-cover"
                  />
                </div>
                <div className="text-left">
                  <p className="font-medium">{post.author.name}</p>
                  <p className="text-sm text-gray-400">{post.author.role}</p>
                </div>
              </div>
              
              <div className="flex items-center text-sm text-gray-400">
                <span>{post.publishDate}</span>
                <span className="mx-2">•</span>
                <span>{post.readTime}</span>
              </div>
            </div>
          </div>
        </div>
      </section>
      
      {/* Featured Image */}
      <section className="w-full bg-gray-950 py-8">
        <div className="container mx-auto px-4 max-w-screen-xl">
          <div className="relative h-[60vh] max-h-[600px] w-full rounded-xl overflow-hidden">
            <Image
              src={post.heroImage}
              alt={post.title}
              fill
              className="object-cover"
              priority
            />
          </div>
        </div>
      </section>
      
      {/* Article Content */}
      <section className="py-16">
        <div className="container mx-auto px-4 max-w-screen-xl">
          <div className="grid grid-cols-1 lg:grid-cols-12 gap-12">
            {/* Sidebar - Table of Contents */}
            <aside className="lg:col-span-3 order-2 lg:order-1">
              <div className="sticky top-24">
                <TableOfContents items={post.tableOfContents} />
                
                <div className="mt-12">
                  <h4 className="text-lg font-bold mb-4">Share this article</h4>
                  <ShareButtons url={`https://refinework.ai/post/${post.id}`} title={post.title} />
                </div>
                
                <div className="mt-12">
                  <h4 className="text-lg font-bold mb-4">Tags</h4>
                  <div className="flex flex-wrap gap-2">
                    {post.tags.map((tag, index) => (
                      <Link
                        key={index}
                        href={`/tag/${tag.toLowerCase().replace(' ', '-')}`}
                        className="bg-gray-800 hover:bg-gray-700 text-sm px-3 py-1 rounded-lg transition-colors"
                      >
                        {tag}
                      </Link>
                    ))}
                  </div>
                </div>
              </div>
            </aside>
            
            {/* Main Content */}
            <article className="lg:col-span-9 order-1 lg:order-2">
              <div 
                className="prose prose-lg prose-invert max-w-none prose-headings:text-white prose-a:text-emerald-400 prose-strong:text-emerald-400 prose-blockquote:border-emerald-400"
                dangerouslySetInnerHTML={{ __html: post.content }}
              />
              
              {/* Author Bio */}
              <div className="mt-16 border-t border-gray-800 pt-12">
                <AuthorCard author={post.author} />
              </div>
              
              {/* Related Articles */}
              <div className="mt-16 border-t border-gray-800 pt-12">
                <h3 className="text-2xl font-bold mb-8">You might also like</h3>
                <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
                  {relatedPosts.map((relatedPost) => (
                    <RelatedPost key={relatedPost.id} post={relatedPost} />
                  ))}
                </div>
              </div>
              
              {/* Comments Section */}
              <div className="mt-16 border-t border-gray-800 pt-12">
                <CommentSection postId={post.id} />
              </div>
            </article>
          </div>
        </div>
      </section>
      
      {/* Newsletter CTA */}
      <section className="py-16 bg-gray-950">
        <div className="container mx-auto px-4 max-w-screen-xl">
          <div className="bg-gradient-to-br from-gray-800 to-gray-900 rounded-xl p-8 md:p-12">
            <div className="grid grid-cols-1 md:grid-cols-2 gap-8 items-center">
              <div>
                <h3 className="text-2xl md:text-3xl font-bold mb-4">Stay ahead with AI insights</h3>
                <p className="text-gray-300 mb-4">Get the latest articles, tutorials, and AI trends delivered directly to your inbox.</p>
              </div>
              <div>
                <div className="flex flex-col sm:flex-row gap-3">
                  <input 
                    type="email" 
                    placeholder="Enter your email" 
                    className="flex-grow px-4 py-3 bg-gray-700 rounded-lg focus:outline-none focus:ring-2 focus:ring-emerald-400"
                  />
                  <button className="px-6 py-3 bg-emerald-500 hover:bg-emerald-600 transition-colors text-gray-900 font-medium rounded-lg whitespace-nowrap">
                    Subscribe
                  </button>
                </div>
                <p className="text-sm text-gray-400 mt-3">Join 25,000+ AI enthusiasts. We respect your privacy.</p>
              </div>
            </div>
          </div>
        </div>
      </section>
      
      {/* Footer - Include the same footer component here */}
      {/* For brevity, I'm not including it in this example */}
    </main>
  );
}